const quotes = [
  // Literary figures
  "It is never too late to be what you might have been. - George Eliot",
  "Not all those who wander are lost. - J.R.R. Tolkien",
  "There is no greater agony than bearing an untold story inside you. - Maya Angelou",
  "We are all in the gutter, but some of us are looking at the stars. - Oscar Wilde",
  "It matters not what someone is born, but what they grow to be. - J.K. Rowling",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
  "The only way out is through. - Robert Frost",
  "In the middle of difficulty lies opportunity. - Albert Einstein",
  "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. - Dr. Seuss",
  "Tomorrow belongs to those who can hear it coming. - David Bowie",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
  "The wound is the place where the Light enters you. - Rumi",
  "Do what you can, with what you have, where you are. - Theodore Roosevelt",
  "Everything you can imagine is real. - Pablo Picasso",
  "One must still have chaos in oneself to be able to give birth to a dancing star. - Friedrich Nietzsche",
  "The mind is everything. What you think you become. - Buddha",
  "If you tell the truth, you don't have to remember anything. - Mark Twain",
  "We become what we think about most of the time. - Earl Nightingale",
  "An unexamined life is not worth living. - Socrates",
  "I think, therefore I am. - Rene Descartes",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
  "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
  "To thine own self be true. - William Shakespeare",
  "There is nothing either good or bad, but thinking makes it so. - William Shakespeare",
  "Hope is the thing with feathers that perches in the soul. - Emily Dickinson",
  "It does not do to dwell on dreams and forget to live. - J.K. Rowling",
  "The journey of a thousand miles begins with a single step. - Lao Tzu",
  "I can be changed by what happens to me. But I refuse to be reduced by it. - Maya Angelou",
  "Life is what happens when you're busy making other plans. - John Lennon",
  "The best time to plant a tree was twenty years ago. The second best time is now. - Chinese Proverb",
  "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
  "Out of the mountain of despair, a stone of hope. - Martin Luther King Jr.",
  "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
 
  // Scientific figures
  "Imagination is more important than knowledge. - Albert Einstein",
  "The important thing is not to stop questioning. Curiosity has its own reason for existing. - Albert Einstein",
  "Nothing in life is to be feared, it is only to be understood. - Marie Curie",
  "Life is not easy for any of us. But what of that? We must have perseverance and confidence in ourselves. - Marie Curie",
  "If I have seen further, it is by standing on the shoulders of giants. - Isaac Newton",
  "The good thing about science is that it's true whether or not you believe in it. - Neil deGrasse Tyson",
  "Somewhere, something incredible is waiting to be known. - Carl Sagan",
  "We are a way for the cosmos to know itself. - Carl Sagan",
  "One, remember to look up at the stars and not down at your feet. - Stephen Hawking",
  "Intelligence is the ability to adapt to change. - Stephen Hawking",
  "The measure of intelligence is the ability to change. - Albert Einstein",
  "In science, there are no shortcuts to truth. - Karl Popper",
  "The scientist is not a person who gives the right answers, he's one who asks the right questions. - Claude Levi-Strauss",
  "Science is a way of thinking much more than it is a body of knowledge. - Carl Sagan",
  "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge. - Daniel J. Boorstin",
  "Equipped with his five senses, man explores the universe around him and calls the adventure Science. - Edwin Hubble",
  "What we know is a drop, what we don't know is an ocean. - Isaac Newton",
  "The only source of knowledge is experience. - Albert Einstein",
  "Genius is one percent inspiration and ninety-nine percent perspiration. - Thomas Edison",
  "The reward of the young scientist is the emotional thrill of being the first person in the history of the world to see or understand something. - Cecilia Payne-Gaposchkin",
  "I was taught that the way of progress was neither swift nor easy. - Marie Curie",
  "Have no fear of perfection, you'll never reach it. - Marie Curie",
  "An expert is a person who has made all the mistakes that can be made in a very narrow field. - Niels Bohr",
  "The universe is under no obligation to make sense to you. - Neil deGrasse Tyson",
  "Everything should be made as simple as possible, but no simpler. - Albert Einstein",
  "Research is what I'm doing when I don't know what I'm doing. - Wernher von Braun",
  "The art of teaching is the art of assisting discovery. - Mark Van Doren",
 
  // Historical figures
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "The best way to predict the future is to create it. - Abraham Lincoln",
  "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
  "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that. - Martin Luther King Jr.",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "No one can make you feel inferior without your consent. - Eleanor Roosevelt",
  "You must be the change you wish to see in the world. - Mahatma Gandhi",
  "Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
  "If you are going through hell, keep going. - Winston Churchill",
  "Never, never, never give up. - Winston Churchill",
  "Well done is better than well said. - Benjamin Franklin",
  "An investment in knowledge pays the best interest. - Benjamin Franklin",
  "Tell me and I forget. Teach me and I remember. Involve me and I learn. - Benjamin Franklin",
  "The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke",
  "Injustice anywhere is a threat to justice everywhere. - Martin Luther King Jr.",
  "Education is the most powerful weapon which you can use to change the world. - Nelson Mandela",
  "It always seems impossible until it's done. - Nelson Mandela",
  "The pen is mightier than the sword. - Edward Bulwer-Lytton",
  "I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character. - Martin Luther King Jr.",
  "A person who never made a mistake never tried anything new. - Albert Einstein",
  "Knowing is not enough; we must apply. Willing is not enough; we must do. - Johann Wolfgang von Goethe",
  "The roots of education are bitter, but the fruit is sweet. - Aristotle",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit. - Aristotle",
  "Knowing yourself is the beginning of all wisdom. - Aristotle",
  "I am not afraid of storms, for I am learning how to sail my ship. - Louisa May Alcott",
  "Turn your wounds into wisdom. - Oprah Winfrey",
  "The purpose of our lives is to be happy. - Dalai Lama",
  "Where there is no struggle, there is no strength. - Oprah Winfrey",
  "Keep your face always toward the sunshine and shadows will fall behind you. - Walt Whitman",
  "Act as if what you do makes a difference. It does. - William James",
  "What you do speaks so loudly that I cannot hear what you say. - Ralph Waldo Emerson",
  "It is during our darkest moments that we must focus to see the light. - Aristotle",
  "Perfection is not attainable, but if we chase perfection we can catch excellence. - Vince Lombardi",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
];
 
export default quotes;